# Generated by Django 4.2.2 on 2024-03-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='static/imgs/')),
                ('name', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(null=True)),
                ('fb', models.TextField(null=True)),
                ('google', models.TextField(null=True)),
                ('insta', models.TextField(null=True)),
                ('youtube', models.TextField(null=True)),
            ],
        ),
    ]
