# Generated by Django 4.2.2 on 2024-03-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_data_tdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
