# Generated by Django 4.2.2 on 2024-03-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_data_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='img',
            field=models.FileField(null=True, upload_to='static/imgs/'),
        ),
    ]
